### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by AftDawn** [c0redumb/midi2vjoy#11]
`C:\Users\Decan\Documents\midi2vjoy-master\midi2vjoy>midi2vjoy.py -m 1 -c LaunchpadMkII.conf -v
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Opening configuration file: LaunchpadMkII.conf
Opening MIDI device: 1
VJoy install path C:\Program Files\vJoy\
Traceback (most recent call last):
  File "C:\Users\Decan\Documents\midi2vjoy-master\midi2vjoy\midi2vjoy.py", line 136, in joystick_run
    vjoy = ctypes.WinDLL(dll_file)
  File "C:\Users\Decan\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Error initializing virtual joysticks

C:\Users\Decan\Documents\midi2vjoy-master\midi2vjoy>`

I am using Nercury's fork of midi2vJoy.

**Comment by AftDawn** [comment]
In the mean time, i'll look out for other midi to controller scripts
