### ISSUE TITLE
Cant get past device selection list

### ISSUE THREAD

**Issue by JSkye3293** [c0redumb/midi2vjoy#7]
Hello, I appreciate this being public however I am having issues getting past the device selection list. It crashes repeatedly, I have all the files installed and localized, I am running Win10 Pro (latest). Here is the output from PowerShell:
My comments are in parentheses.

(1st Attempt)

PS C:\Users\skyj3\Desktop\midi2vjoy-master\midi2vjoy-master\midi2vjoy> python.exe .\midi2vjoy.py -t
pygame 1.9.6                                                                                                            
Hello from the pygame community. https://www.pygame.org/contribute.html                                                 
Input MIDI devices:                                                                                                     
1 loopMIDI Port
2 loopMIDI Port 1                                                                                                       
3 JSkye-slayer                                                                 
4 WORLDE easy control
Select MIDI device to test: JSkye-slayer                                                                                
Traceback (most recent call last):
File ".\midi2vjoy.py", line 199, in <module>
	main()
File ".\midi2vjoy.py", line 192, in main
	midi_test()
File ".\midi2vjoy.py", line 45, in midi_test
	d = int(input('Select MIDI device to test: '))
ValueError: invalid literal for int() with base 10: 'JSkye-slayer'

(The one above I realized what I did wrong)

(2nd attempt)

PS C:\Users\skyj3\Desktop\midi2vjoy-master\midi2vjoy-master\midi2vjoy> python.exe .\midi2vjoy.py -t
pygame 1.9.6                                                                                                            
Hello from the pygame community. https://www.pygame.org/contribute.html                                                 
Input MIDI devices:                                                                                                     
1 loopMIDI Port
2 loopMIDI Port 1                                                                                                       
3 JSkye-slayer                                                                 
4 WORLDE easy control
Select MIDI device to test:3
Opening MIDI device: 3
Fatal Python error: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00002f54 (most recent call first):
  File "C:\Users\skyj3\AppData\Local\Programs\Python\Python38\lib\site-packages\pygame\midi.py", line 280 in __init__
  File ".\midi2vjoy.py", line 50 in midi_test
  File ".\midi2vjoy.py", line 192 in main
  File ".\midi2vjoy.py", line 199 in <module>

(3rd attempt)

PS C:\Users\skyj3\Desktop\midi2vjoy-master\midi2vjoy-master\midi2vjoy> python.exe .\midi2vjoy.py -t
pygame 1.9.6                                                                                                            
Hello from the pygame community. https://www.pygame.org/contribute.html                                                 
Input MIDI devices:                                                                                                     
1 loopMIDI Port
2 loopMIDI Port 1                                                                                                       
3 JSkye-slayer                                                                 
4 WORLDE easy control
Select MIDI device to test:4
Opening MIDI device: 4
Traceback (most recent call last):
  File ".\midi2vjoy.py", line 50, in midi_test
    m = pygame.midi.Input(d)
  File "C:\Users\skyj3\AppData\Local\Programs\Python\Python38\lib\site-packages\pygame\midi.py", line 280, in __init__
    self._input = _pypm.Input(device_id, buffer_size)
  File "pypm.pyx", line 531, in pypm.Input.__init__
Exception: b"PortMidi: `Host error'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\midi2vjoy.py", line 199, in <module>
    main()
  File ".\midi2vjoy.py", line 192, in main
    midi_test()
  File ".\midi2vjoy.py", line 57, in midi_test
    m.close()
UnboundLocalError: local variable 'm' referenced before assignment

(4th attempt)

PS C:\Users\skyj3\Desktop\midi2vjoy-master\midi2vjoy-master\midi2vjoy> python.exe .\midi2vjoy.py -t
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Input MIDI devices:
1 loopMIDI Port
2 loopMIDI Port 1
3 JSkye-slayer
4 WORLDE easy control
Select MIDI device to test: 1
Opening MIDI device: 1
Fatal Python error: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00005228 (most recent call first):
  File "C:\Users\skyj3\AppData\Local\Programs\Python\Python38\lib\site-packages\pygame\midi.py", line 280 in __init__
  File ".\midi2vjoy.py", line 50 in midi_test
  File ".\midi2vjoy.py", line 192 in main
  File ".\midi2vjoy.py", line 199 in <module>
PS C:\Users\skyj3\Desktop\midi2vjoy-master\midi2vjoy-master\midi2vjoy>

(I gave up after this one)

Many thanks in advance! Willing to help to the best of my ability however im better at C++. 
-JSkye3293

**Comment by JamieJanssen** [comment]
I got the same error. Something wrong with this version of Pygame?

**Comment by bafonso** [comment]
I'm getting the same. My pygame version is 1.9.6 on this PC.
